### ISSUE TITLE
Please contact me

### ISSUE THREAD

**Issue by NiekAndresen** [dolokov/multitracker#2]
somehow my mails don't come though :/
Not urgent though.
One thing, in app/app.py there is an include of predict, which doesn't exist anymore I think.

**Comment by NiekAndresen** [comment]
There is no __init__.py in multitracker/object_detection

Also the import "from object_detection.utils..." (in object_detection/finetune.py) does not work.

**Comment by dolokov** [comment]
Hi,

you are right about the rogue import. [fixed it](https://github.com/dolokov/multitracker/commit/80ad62752d1f4b97626c52b4505a95e811faecd5).

Have you installed the Object Detection API from Google? If not, please follow these instructions to get you up to warp speed:  https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2.md 

Cheers 
Alex

**Comment by NiekAndresen** [comment]
thanks.
